name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      uses: actions/docker/cli@master
      with:
        args: build -t ldhertert/harness-cv-testapp:${GITHUB_SHA}
        
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ldhertert
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
  push:
    runs-on: ubuntu-latest
    needs: 
      - build
      - login
    steps:
    - name: Push to Docker Hub
      uses: actions/docker/cli@master
      with:
        args: push ldhertert/harness-cv-testapp:${GITHUB_SHA}
