name: Publish to nexus

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build zip artifact
      run: |
        cat package.json | grep '"version":' |  awk '{print $2}' | sed 's/"//g' | sed 's/,//g' > $GITHUB_WORKSPACE/version
        mkdir ./dist
        zip -r "./dist/harness-cv-testapp.zip" ./package.json ./src
        ls ./dist
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to nexus
      run: mvn deploy:deploy-file -DgroupId=harness-sample-apps -DartifactId=harness-cv-testapp2 -Dversion=1.0.0 -Dpackaging=zip -Dfile=./dist/harness-cv-testapp.zip -DgeneratePom=true -DupdateReleaseInfo=true -Durl="https://admin:${{ secrets.nexusPassword }}@nexusv3.tools.harnessio.se/repository/maven-releases/"
    #- name: Publish to nexus
    #  uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
    #  with:
    #    serverUrl: https://nexusv3.tools.harnessio.se/
    #    username: admin
    #    password: ${{ secrets.nexusPassword }}
    #    format: maven2
    #    repository: maven-releases
    #    coordinates: "groupId=harness-sample-apps artifactId=harness-cv-testapp version=$(cat $GITHUB_WORKSPACE/version)"
    #    assets: extension=zip
    #    filename: "./dist/harness-cv-testapp.$(cat $GITHUB_WORKSPACE/version).zip"
        #filename: "./dist/harness-cv-testapp.1.0.3.zip"
