name: Publish to nexus

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build zip artifact
      run: |
        mkdir ./dist
        zip -r "./dist/harness-cv-testapp.${GITHUB_REF##*/}.zip" ./package.json ./src
        #zip -r "./dist/harness-cv-testapp.1.0.3.zip" ./package.json ./src
        ls ./dist
    - name: Publish to nexus
      uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
      with:
        serverUrl: https://nexusv3.tools.harnessio.se/
        username: admin
        password: ${{ secrets.nexusPassword }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=harness-sample-apps artifactId=harness-cv-testapp version=1.0.3
        assets: extension=zip
        filename: "./dist/harness-cv-testapp.${GITHUB_REF##*/}.zip"
        #filename: "./dist/harness-cv-testapp.1.0.3.zip"
